store/pos/urls.py
from . import views
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path
from django.views.generic.base import RedirectView

handler403 = views.error_403
app_name = 'pos'
urlpatterns = [
    path('pos', views.pos, name="pos-page"),
    path('checkout-modal', views.checkout_modal, name="checkout-modal"),
    path('save-pos', views.save_pos, name="save-pos"),
    path('sales', views.salesList, name="sales-page"),
    path('receipt', views.receipt, name="receipt-modal"),
    path('delete_sale', views.delete_sale, name="delete-sale"),
]   

store/report/urls.py
from django.urls import path
from .views.views_sales_pdf import *
from .views.views_sales_excel import *
from .views.views_purchase_pdf import *
from .views.views_purchase_excel import *
from .views.views_profit_pdf import *
from .views.views_profit_excel import *
from .views.views_miscelanea import *
from .views.views_mix_excel import *
app_name = 'report'

urlpatterns = [
    # Reportes PDF
    path('sales_report/', SalesReportView.as_view(), name='sales_report'),
    path('generate-pdf-sales/', GeneratePDFSalesView.as_view(), name='generate_pdf_sales'),
    path('generate-pdf-sales-year/', GeneratePDFSalesYearView.as_view(), name='generate_pdf_sales_year'),
    path('generate-pdf-sales-month/', GeneratePDFSalesMonthView.as_view(), name='generate_pdf_sales_month'),
    path('generatepdf_sales_day/', GeneratePDFSalesDayView.as_view(), name='generatepdf_sales_day'),
    path('sales-report-custom/', SalesReportCustomView.as_view(), name='sales_report_custom'),

    # # Reportes Excel
    path('generate_excel_sales/', GenerateExcelSalesView.as_view(), name='generate_excel_sales'),
    path('generate_excel_sales_year/', GenerateExcelSalesYearView.as_view(), name='generate_excel_sales_year'),
    path('generate_excel_sales_month/', GenerateExcelSalesMonthView.as_view(), name='generate_excel_sales_month'),
    path('generate_excel_sales_day/', GenerateExcelSalesDayView.as_view(), name='generate_excel_sales_day'),
    
    #Reporte Compras    
    path('reporte_compras/', PurchaseReportView.as_view(), name='reporte_compras'),
    path('generate-pdf-purchase/', GeneratePDFPurchaseView.as_view(), name='purchase_pdf'),
    path('generate-pdf-purchase-year/', YearlyPDFPurchaseView.as_view(), name='purchase_year_pdf'),
    path('generate-pdf-purchase-month/', MonthlyPDFPurchaseView.as_view(), name='purchase_month_pdf'),
    path('generate-pdf-purchase-day/', DailyPDFPurchaseView.as_view(), name='purchase_day_pdf'),
    
    path('generate-excel-purchase/', GenerateExcelPurchaseView.as_view(), name='purchase_excel'),
    path('generate-excel-purchase-year/', ExcelPurchaseYearView.as_view(), name='purchase_year_excel'),
    path('generate-excel-purchase-month/', ExcelPurchaseMonthView.as_view(), name='purchase_month_excel'),
    path('generate-excel-purchase-day/', ExcelPurchaseDayView.as_view(), name='purchase_day_excel'),
    
    #Reporte Ganancias
    path('profit-report/', ProfitReportView.as_view(), name='profit_report'),
    path('generate-pdf-profit/', GeneratePDFProfitView.as_view(), name='profit_pdf'),
    path('generate-pdf-profit-year/', YearlyPDFProfitView.as_view(), name='profit_year_pdf'),
    path('generate-pdf-profit-month/', MonthlyPDFProfitView.as_view(), name='profit_month_pdf'),
    path('generate-pdf-profit-day/', DailyPDFProfitView.as_view(), name='profit_day_pdf'),
    
    path('generate-excel-profit/', GenerateExcelProfitView.as_view(), name='profit_excel'),
    path('generate-excel-profit-year/', YearlyExcelProfitView.as_view(), name='profit_year_excel'),
    path('generate-excel-profit-month/', MonthlyExcelProfitView.as_view(), name='profit_month_excel'),
    path('generate-excel-profit-day/', DailyExcelProfitView.as_view(), name='profit_day_excel'),
    
    # miscelanea report
    path('mix-report/', MixReportView.as_view(), name='mix_report'),
    path('supplier-pdf/', SupplierPDFView.as_view(), name='supplier_pdf'),
    path('supplier-product-pdf/', SupplierProductPDFView.as_view(), name='supplier_product_pdf'),
    path('product-pdf/', ProductPDFView.as_view(), name='product_pdf'),
    path('productqty-pdf/', ProductPDFQtyView.as_view(), name='productqty_pdf'),
    
    path('supplier-excel/', SupplierExcelView.as_view(), name='supplier_excel'),
    path('supplier-product-excel/', SupplierProductExcelView.as_view(), name='supplier_product_excel'),
    path('product-excel/', ProductExcelView.as_view(), name='product_excel'),
    path('product-qty-excel/', ProductQtyExcelView.as_view(), name='productqty_excel'),
    
    path('mix-sales-pdf/', MixPDFSalesDayView.as_view(), name='mix_sales_pdf'),
    path('mix-tramo-sales-pdf/', MixTramoPDFSalesDayView.as_view(), name='mixtramo_sales_pdf'),
    
    path('mix-day-excel/', MixExcelSalesDayView.as_view(), name='mix_sales_excel'),
    path('mix-section-day-excel/', MixTramoExcelSalesDayView.as_view(), name='mix_sectionsales_excel'),
]

store/store/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('inventory/', include('inventory.urls')),
    
    path('pos/', include('pos.urls')),
    path('purchase/', include('purchase.urls')),
    path('report/', include('report.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/purchase/models.py
from django.db import models
from django.db.models.signals import post_save, post_delete
from django.dispatch import receiver
from django.utils import timezone
from django.db.models import Sum
from inventory.models import Products
from django.db import transaction
from django.db import models, transaction
from decimal import Decimal
from django.core.exceptions import ValidationError
class Supplier(models.Model):
    name = models.CharField(max_length=100)
    contact_info = models.TextField(blank=True)
    date_added = models.DateTimeField(default=timezone.now, editable=False)
    date_updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name
    
    
    
class PurchaseProduct(models.Model):
    supplier = models.ForeignKey(Supplier, on_delete=models.SET_NULL, null=True)
    product = models.ForeignKey(Products, on_delete=models.SET_NULL, null=True)
    cost = models.DecimalField(max_digits=18, decimal_places=8, default=0)
    qty = models.DecimalField(max_digits=10, decimal_places=0, default=0)
    total = models.DecimalField(max_digits=18, decimal_places=8, editable=False, default=0)
    date_added = models.DateTimeField(default=timezone.now)
    date_updated = models.DateTimeField(auto_now=True)

    def clean(self):
        if self.qty <= 0:
            raise ValidationError("The quantity must be greater than zero.")
        if self.cost <= 0:
            raise ValidationError("The cost must be greater than zero.")

    def save(self, *args, **kwargs):
        self.clean()
        self.total = self.cost * self.qty
        
        with transaction.atomic():
            
            if self.pk:
            
                previous_instance = PurchaseProduct.objects.get(pk=self.pk)
                quantity_difference = self.qty - previous_instance.qty
            else:
                quantity_difference = self.qty
            super().save(*args, **kwargs)

            # Actualizar el producto asociado
            if self.product:
                self.product.update_quantity_on_purchase(quantity_difference)
                self.product.update_cost(self.cost)
                
                
    def delete(self, *args, **kwargs):
        with transaction.atomic():
            if self.product:
                # Actualizar el producto asociado antes de eliminar la compra
                self.product.decrease_quantity(self.qty)
                self.product.update_cost_after_deletion(self.cost)
            super().delete(*args, **kwargs)
            
    def __str__(self):
        return f"{self.product} de {self.supplier} - {self.qty} @ {self.cost} cada uno"

    

store/report/models.py
from django.db import models

# Create your models here.

store/report/forms.py
from django import forms
from pos.models import Sales
from datetime import datetime
from django import forms

from purchase.models import *
MONTH_NAMES = [
    'January', 'February', 'March', 'April', 'May', 'June',
    'July', 'August', 'September', 'October', 'November', 'December'
]


MONTH_CHOICES = [(str(i), month) for i, month in enumerate(MONTH_NAMES, 1)]


DAYS_OF_WEEK = {
    'Monday': 'Lunes',
    'Tuesday': 'Martes',
    'Wednesday': 'Miércoles',
    'Thursday': 'Jueves',
    'Friday': 'Viernes',
    'Saturday': 'Sábado',
    'Sunday': 'Domingo'
}

class SalesReportForm(forms.Form):
    start_date = forms.DateField(required=False, widget=forms.DateInput(attrs={'type': 'date'}))
    end_date = forms.DateField(required=False, widget=forms.DateInput(attrs={'type': 'date'}))
    customer = forms.CharField(max_length=100, required=False)


class YearMonthForm(forms.Form):
    year = forms.IntegerField(label="Year", min_value=1900, max_value=2100)
    month = forms.ChoiceField(label="Month", choices=MONTH_CHOICES)


class YearForm(forms.Form):
    year = forms.IntegerField(label="Year", min_value=1900, max_value=2100)


class DayForm(forms.Form):
    year = forms.IntegerField(label="Year", min_value=1900, max_value=2100)
    month = forms.ChoiceField(label="Month", choices=MONTH_CHOICES)
    day = forms.IntegerField(label="Day", min_value=1, max_value=31)


class DateRangeForm(forms.Form):
    start_date = forms.DateField(label="Start Date", widget=forms.DateInput(attrs={'type': 'date'}))
    end_date = forms.DateField(label="End Date", widget=forms.DateInput(attrs={'type': 'date'}))


class ReportForm(forms.Form):
    pass

class MonthReportForm(forms.Form):
    year = forms.IntegerField(label='Year', min_value=1900, max_value=datetime.now().year)
    month = forms.IntegerField(label='Month', min_value=1, max_value=12)

class DayReportForm(forms.Form):
    year = forms.IntegerField(label='Year', min_value=1900, max_value=datetime.now().year)
    month = forms.IntegerField(label='Month', min_value=1, max_value=12)
    day = forms.IntegerField(label='Day', min_value=1, max_value=31)

class PurchaseReportForm(forms.Form):
    start_date = forms.DateField(required=False, widget=forms.TextInput(attrs={'type': 'date'}))
    end_date = forms.DateField(required=False, widget=forms.TextInput(attrs={'type': 'date'}))
    supplier = forms.ModelChoiceField(queryset=Supplier.objects.all(), required=False)


class YearReportForm(forms.Form):
    current_year = datetime.now().year
    YEAR_CHOICES = [(year, year) for year in range(current_year - 10, current_year + 1)]

    year = forms.ChoiceField(choices=YEAR_CHOICES, required=True, label="Select Year", widget=forms.Select)

class MonthYearReportForm(forms.Form):
    year = forms.IntegerField(min_value=2000, max_value=timezone.now().year, label='Year')
    month = forms.IntegerField(min_value=1, max_value=12, label='Month')

class DayMonthYearReportForm(forms.Form):
    year = forms.IntegerField(min_value=2000, max_value=timezone.now().year, label='Year')
    month = forms.IntegerField(min_value=1, max_value=12, label='Month')
    day = forms.IntegerField(min_value=1, max_value=31, label='Day')  # Note: Does not validate specific days for each month

class DayTramoForm(forms.Form):
    start_year = forms.IntegerField(label='Start Year', min_value=2023)
    start_month = forms.ChoiceField(label='Start Month', choices=[
        ('', 'Month'),
        (1, 'January'),
        (2, 'February'),
        (3, 'March'),
        (4, 'April'),
        (5, 'May'),
        (6, 'June'),
        (7, 'July'),
        (8, 'August'),
        (9, 'September'),
        (10, 'October'),
        (11, 'November'),
        (12, 'December'),
    ])
    start_day = forms.IntegerField(label='Start Day', min_value=1, max_value=31)

    end_year = forms.IntegerField(label='End Year', min_value=2023)
    end_month = forms.ChoiceField(label='End Month', choices=[
        ('', 'Month'),
        (1, 'January'),
        (2, 'February'),
        (3, 'March'),
        (4, 'April'),
        (5, 'May'),
        (6, 'June'),
        (7, 'July'),
        (8, 'August'),
        (9, 'September'),
        (10, 'October'),
        (11, 'November'),
        (12, 'December'),
    ])
    end_day = forms.IntegerField(label='End Day', min_value=1, max_value=31)

store/report/templates/report/mix_day_pdf.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Daily Sales Report</title>
    <style>
        body { font-family: Arial, sans-serif; font-size: 12px; }
        table { width: 100%; border-collapse: collapse; }
        th, td { border: 1px solid black; padding: 8px; text-align: left; }
        th { background-color: #f2f2f2; }
    </style>
</head>
<body>
    <h2>Daily Sales Report</h2>
    <p>Date: {{day_name}}, {{ day }}/{{ month_name }}/{{ year }}</p>
    <p>Total Customers: {{ total_customers }}</p>
    <p>Total Items Sold: {{ total_items_sold }}</p>
    <p>Total Income: {{ total_income }}</p>
    <p>Total Net Profit: {{ total_net_profit|floatformat:2 }}</p>
    <table>
        <thead>
            <tr>
                <th>Date</th>
                <th>Customer</th>
                <th>Products Sold Quantity</th>
                <th>Unit Price - Unit Cost</th>
                <th>Grand Total</th>
                <th>Net Profit</th>
            </tr>
        </thead>
        <tbody>
            {% for sale in sale_data %}
            <tr>
                <td>{{ sale.date_added }}</td>
                <td>{{ sale.customer }}</td>
                <td>
                    <ul>
                        {% for product, details in sale.products_list.items %}
                        <li>{{ product }}: {{ details.qty }}</li>
                        {% endfor %}
                    </ul>
                </td>
                <td>
                    <ul>
                        {% for product, details in sale.products_list.items %}
                        <li>{{ product }}: {{ details.price }} - {{ details.cost }}</li>
                        {% endfor %}
                    </ul>
                </td>
                <td>{{ sale.grand_total }}</td>
                <td>{{ sale.net_profit|floatformat:2 }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</body>
</html>

store/report/templates/report/mix_products_pdf.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Product List</title>
    <style>
        body {
            font-family: Arial, sans-serif;
        }
        .table {
            width: 100%;
            border-collapse: collapse;
        }
        .table th, .table td {
            border: 1px solid #000;
            padding: 8px;
            text-align: left;
        }
        .table th {
            background-color: #f2f2f2;
        }
    </style>
</head>
<body>
    <h1>Product List</h1>
    <p>Generation Date: {{ current_date }}</p>
    <table class="table">
        <thead>
            <tr>
                <th>Name</th>
                <th>Description</th>
                <th>Date Added</th>
            </tr>
        </thead>
        <tbody>
            {% for product in products %}
            <tr>
                <td>{{ product.name }}</td>
                <td>{{ product.description }}</td>
                <td>{{ product.date_added }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</body>
</html>

store/report/templates/report/mix_supplier_product_pdf.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>List of Suppliers and Products</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 30px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: #f2f2f2;
        }
    </style>
</head>
<body>
    
    <h2>List of Suppliers and Products</h2>
    <p>Report Generation Date: {{ current_date|date:"d/m/Y H:i:s" }}</p>
    
    {% for supplier in suppliers %}
        <h3>{{ supplier.name }}</h3>
        <table>
            <thead>
                <tr>
                    <th>Product</th>
                    <th>Cost Per Unit</th>
                    <th>Quantity</th>
                    <th>Acquisition Date</th>
                </tr>
            </thead>
            <tbody>
                {% for purchase_product in supplier.purchaseproduct_set.all %}
                    <tr>
                        <td>{{ purchase_product.product.name }}</td>
                        <td>{{ purchase_product.cost }}</td>
                        <td>{{ purchase_product.qty }}</td>
                        <td>{{ purchase_product.date_added }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% endfor %}
</body>
</html>

store/report/templates/report/profit_report.html
{% extends 'base.html' %}

{% block pageContent %}

{% load humanize %}
<style>
    .mdc-card {
        padding: 8px !important;
    }

    .card-title {
        margin-bottom: 4px !important;
    }

    .mdc-layout-grid__cell {
        padding: 4px !important;
    }

    .button-group .mdc-button {
        margin: 4px !important;
        padding: 4px 8px !important;
    }
</style>

<div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-12">
    <div class="mdc-card py-1">
        <div class="d-flex justify-content-between align-items-center">
            <h4 class="card-title mb-0">Profit Report</h4>
        </div>
    </div>
</div>

<div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-4">
    <div class="mdc-card py-1">
        <h5 class="card-title">Annual Report</h5>
        <form id="yearly-report-form" class="form" method="post" action="{% url 'report:profit_year_pdf' %}">
            {% csrf_token %}
            <div class="mdc-layout-grid">
                <div class="mdc-layout-grid__inner">
                    <div class="mdc-layout-grid__cell mdc-layout-grid__cell--span-10">
                        <input id="year" type="number" name="year" placeholder="Year"
                            class="mdc-text-field__input custom-year-input" min="2023" max="{{ max_year }}">
                    </div>
                </div>
                <div class="mdc-layout-grid__cell mdc-layout-grid__cell--span-6 d-flex justify-content-end align-items-center">
                    <div class="mdc-card py-1">
                        <h4 class="card-title mb-0">Generate Reports</h4>
                        <div class="button-group">
                            <button type="button" onclick="generateYearPDF()" class="mdc-button mdc-button--raised mdc-button--dense mdc-button--outlined icon-button">
                                <i class="material-icons">picture_as_pdf</i> PDF
                            </button>
                            <button type="button" onclick="generateYearExcel()" class="mdc-button mdc-button--raised mdc-button--dense mdc-button--outlined icon-button">
                                <i class="material-icons">description</i> Excel
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

<div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-4">
    <div class="mdc-card py-1">
        <h5 class="card-title">Monthly Report</h5>
        <form id="monthly-report-form" class="form" method="post" action="{% url 'report:profit_month_pdf' %}">
            {% csrf_token %}
            <div class="mdc-layout-grid">
                <div class="mdc-layout-grid__inner">
                    <div class="mdc-layout-grid__cell mdc-layout-grid__cell--span-10">
                        <input id="year" type="number" name="year" placeholder="Year"
                            class="mdc-text-field__input custom-year-input" min="2023" max="{{ max_year }}">
                    </div>
                    <div class="mdc-layout-grid__cell mdc-layout-grid__cell--span-10">
                        <select id="month" name="month" class="mdc-text-field__input custom-month-input">
                            <option value="" disabled selected>Month</option>
                            <option value="1">January</option>
                            <option value="2">February</option>
                            <option value="3">March</option>
                            <option value="4">April</option>
                            <option value="5">May</option>
                            <option value="6">June</option>
                            <option value="7">July</option>
                            <option value="8">August</option>
                            <option value="9">September</option>
                            <option value="10">October</option>
                            <option value="11">November</option>
                            <option value="12">December</option>
                        </select>
                    </div>
                </div>
                <div class="mdc-layout-grid__cell mdc-layout-grid__cell--span-6 d-flex justify-content-end align-items-center">
                    <div class="mdc-card py-1">
                        <h4 class="card-title mb-0">Generate Reports</h4>
                        <div class="button-group">
                            <button type="button" onclick="generateMonthPDF()" class="mdc-button mdc-button--raised mdc-button--dense mdc-button--outlined icon-button">
                                <i class="material-icons">picture_as_pdf</i> PDF
                            </button>
                            <button type="button" onclick="generateMonthExcel()" class="mdc-button mdc-button--raised mdc-button--dense mdc-button--outlined icon-button">
                                <i class="material-icons">description</i> Excel
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

<div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-4">
    <div class="mdc-card py-1">
        <h5 class="card-title">Daily Report</h5>
        <form id="daily-report-form" class="form" method="post" action="{% url 'report:profit_day_pdf' %}">
            {% csrf_token %}
            <div class="mdc-layout-grid">
                <div class="mdc-layout-grid__inner">
                    <div class="mdc-layout-grid__cell mdc-layout-grid__cell--span-10">
                        <input id="year" type="number" name="year" placeholder="Year"
                            class="mdc-text-field__input custom-year-input" min="2023" max="{{ max_year }}">
                    </div>
                    <div class="mdc-layout-grid__cell mdc-layout-grid__cell--span-10">
                        <select id="month" name="month" class="mdc-text-field__input custom-month-input">
                            <option value="" disabled selected>Month</option>
                            <option value="1">January</option>
                            <option value="2">February</option>
                            <option value="3">March</option>
                            <option value="4">April</option>
                            <option value="5">May</option>
                            <option value="6">June</option>
                            <option value="7">July</option>
                            <option value="8">August</option>
                            <option value="9">September</option>
                            <option value="10">October</option>
                            <option value="11">November</option>
                            <option value="12">December</option>
                        </select>
                    </div>
                    <div class="mdc-layout-grid__cell mdc-layout-grid__cell--span-10">
                        <input id="day" type="number" name="day" placeholder="Day" class="mdc-text-field__input" min="1"
                            max="31">
                    </div>
                </div>
                <div class="mdc-layout-grid__cell mdc-layout-grid__cell--span-6 d-flex justify-content-end align-items-center">
                    <div class="mdc-card py-1">
                        <h4 class="card-title mb-0">Generate Reports</h4>
                        <div class="button-group">
                            <button type="button" onclick="generateDayPDF()" class="mdc-button mdc-button--raised mdc-button--dense mdc-button--outlined icon-button">
                                <i class="material-icons">picture_as_pdf</i> PDF
                            </button>
                            <button type="button" onclick="generateDayExcel()" class="mdc-button mdc-button--raised mdc-button--dense mdc-button--outlined icon-button">
                                <i class="material-icons">description</i> Excel
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

<div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-12">
    <div class="mdc-card py-1">
        <form id="general-report-form" method="post">
            {% csrf_token %}
            <div class="mdc-layout-grid">
                <div class="mdc-layout-grid__inner">
                    <div class="mdc-layout-grid__cell mdc-layout-grid__cell--span-6">
                        <div class="mdc-card py-1">
                            <h4 class="card-title mb-0">Earnings Summary</h4>
                            <p>Total Sales: {{ total_ingresos|floatformat:2|intcomma }} Bs</p>
                            <p>Total Costs: {{ total_costos|floatformat:2|intcomma }} Bs</p>
                            <p>Total Profits: {{ total_ganancias|floatformat:2|intcomma }} Bs</p>
                        </div>
                    </div>
                    <div class="mdc-layout-grid__cell mdc-layout-grid__cell--span-6 d-flex justify-content-end align-items-center">
                        <div class="mdc-card py-1">
                            <h4 class="card-title mb-0">General Reports</h4>
                            <div class="button-group">
                                <button type="button" onclick="generateGeneralPDF()" class="mdc-button mdc-button--raised mdc-button--dense mdc-button--outlined icon-button">
                                    <i class="material-icons">picture_as_pdf</i> PDF
                                </button>
                                <button type="button" onclick="generateGeneralExcel()" class="mdc-button mdc-button--raised mdc-button--dense mdc-button--outlined icon-button">
                                    <i class="material-icons">description</i> Excel
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

<script>
    function generateYearPDF() {
        const year = document.getElementById('year').value;
        if (year) {
            const form = document.getElementById('yearly-report-form');
            form.action = `{% url 'report:profit_year_pdf' %}?year=` + year;
            form.submit();
        } else {
            alert('Please enter a year.');
        }
    }

    function generateYearExcel() {
        const year = document.getElementById('year').value;
        if (year) {
            const form = document.getElementById('yearly-report-form');
            form.action = `{% url 'report:profit_year_excel' %}?year=` + year;
            form.submit();
        } else {
            alert('Please enter a year.');
        }
    }

    function generateMonthPDF() {
        const year = document.getElementById('year').value;
        const month = document.getElementById('month').value;
        if (year && month) {
            const form = document.getElementById('monthly-report-form');
            form.action = `{% url 'report:profit_month_pdf' %}?year=` + year + '&month=' + month;
            form.submit();
        } else {
            alert('Please enter a year and select a month.');
        }
    }

    function generateMonthExcel() {
        const year = document.getElementById('year').value;
        const month = document.getElementById('month').value;
        if (year && month) {
            const form = document.getElementById('monthly-report-form');
            form.action = `{% url 'report:profit_month_excel' %}?year=` + year + '&month=' + month;
            form.submit();
        } else {
            alert('Please enter a year and select a month.');
        }
    }

    function generateDayPDF() {
        const year = document.getElementById('year').value;
        const month = document.getElementById('month').value;
        const day = document.getElementById('day').value;
        if (year && month && day) {
            const form = document.getElementById('daily-report-form');
            form.action = `{% url 'report:profit_day_pdf' %}?year=` + year + '&month=' + month + '&day=' + day;
            form.submit();
        } else {
            alert('Please enter a year, select a month, and enter a day.');
        }
    }

    function generateDayExcel() {
        const year = document.getElementById('year').value;
        const month = document.getElementById('month').value;
        const day = document.getElementById('day').value;
        if (year && month && day) {
            const form = document.getElementById('daily-report-form');
            form.action = `{% url 'report:profit_day_excel' %}?year=` + year + '&month=' + month + '&day=' + day;
            form.submit();
        } else {
            alert('Please enter a year, select a month, and enter a day.');
        }
    }

    // function generateGeneralPDF() {
    //     const form = document.getElementById('general-report-form');
    //     form.action = `{% url 'report:profit_general_pdf' %}`;
    //     form.submit();
    // }

    // function generateGeneralExcel() {
    //     const form = document.getElementById('general-report-form');
    //     form.action = `{% url 'report:profit_general_excel' %}`;
    //     form.submit();
    // }
</script>

{% endblock %}