store/inventory/urls.py
from . import views
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path
from django.views.generic.base import RedirectView
from .views import *
app_name = 'inventory'
urlpatterns = [
    path('category/', CategoryList.as_view(), name='category_list'),
    path('category/new/', CategoryCreate.as_view(), name='category_create'),
    path('category/edit/<int:pk>/', CategoryUpdate.as_view(), name='category_update'),
    path('category/delete/<int:pk>/', CategoryDelete.as_view(), name='category_delete'),
    path('category/<int:pk>/products/', CategoryProductsList.as_view(), name='category_products'),

    
    path('products/', ProductList.as_view(), name='product_list'),
    path('products/new/', ProductCreate.as_view(), name='product_create'),
    path('products/edit/<int:pk>/', ProductUpdate.as_view(), name='product_update'),
    path('products/delete/<int:pk>/', ProductDelete.as_view(), name='product_delete'),
    path('products/<int:pk>/', views.ProductDetailView.as_view(), name='product_detail'),
    
]

store/pos/urls.py
from . import views
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path
from django.views.generic.base import RedirectView

handler403 = views.error_403
app_name = 'pos'
urlpatterns = [
    path('pos', views.pos, name="pos-page"),
    path('checkout-modal', views.checkout_modal, name="checkout-modal"),
    path('save-pos', views.save_pos, name="save-pos"),
    path('sales', views.salesList, name="sales-page"),
    path('receipt', views.receipt, name="receipt-modal"),
    path('delete_sale', views.delete_sale, name="delete-sale"),
]   

store/purchase/urls.py
from django.urls import path
from .views import *
app_name = 'purchase'

urlpatterns = [
    path('suppliers/', SupplierList.as_view(), name='supplier_list'),
    path('suppliers/new/', SupplierCreate.as_view(), name='supplier_create'),
    path('suppliers/edit/<int:pk>/', SupplierUpdate.as_view(), name='supplier_update'),
    path('suppliers/delete/<int:pk>/', SupplierDelete.as_view(), name='supplier_delete'),
    
    path('purchase/', PurchaseList.as_view(), name='purchase_list'),
    path('purchase/new/', PurchaseCreate.as_view(), name='purchase_create'),
    path('purchase/edit/<int:pk>/', PurchaseUpdate.as_view(), name='purchase_update'),
    path('purchase/delete/<int:pk>/', PurchaseDelete.as_view(), name='purchase_delete'),
]

store/report/urls.py
from django.urls import path
from .views.views_sales_pdf import *
from .views.views_sales_excel import *
from .views.views_purchase_pdf import *
from .views.views_purchase_excel import *
from .views.views_profit_pdf import *
from .views.views_profit_excel import *
from .views.views_miscelanea import *
from .views.views_mix_excel import *
app_name = 'report'

urlpatterns = [
    # Reportes PDF
    path('sales_report/', SalesReportView.as_view(), name='sales_report'),
    path('generate-pdf-sales/', GeneratePDFSalesView.as_view(), name='generate_pdf_sales'),
    path('generate-pdf-sales-year/', GeneratePDFSalesYearView.as_view(), name='generate_pdf_sales_year'),
    path('generate-pdf-sales-month/', GeneratePDFSalesMonthView.as_view(), name='generate_pdf_sales_month'),
    path('generatepdf_sales_day/', GeneratePDFSalesDayView.as_view(), name='generatepdf_sales_day'),
    path('sales-report-custom/', SalesReportCustomView.as_view(), name='sales_report_custom'),

    # # Reportes Excel
    path('generate_excel_sales/', GenerateExcelSalesView.as_view(), name='generate_excel_sales'),
    path('generate_excel_sales_year/', GenerateExcelSalesYearView.as_view(), name='generate_excel_sales_year'),
    path('generate_excel_sales_month/', GenerateExcelSalesMonthView.as_view(), name='generate_excel_sales_month'),
    path('generate_excel_sales_day/', GenerateExcelSalesDayView.as_view(), name='generate_excel_sales_day'),
    
    #Reporte Compras    
    path('reporte_compras/', PurchaseReportView.as_view(), name='reporte_compras'),
    path('generate-pdf-purchase/', GeneratePDFPurchaseView.as_view(), name='purchase_pdf'),
    path('generate-pdf-purchase-year/', YearlyPDFPurchaseView.as_view(), name='purchase_year_pdf'),
    path('generate-pdf-purchase-month/', MonthlyPDFPurchaseView.as_view(), name='purchase_month_pdf'),
    path('generate-pdf-purchase-day/', DailyPDFPurchaseView.as_view(), name='purchase_day_pdf'),
    
    path('generate-excel-purchase/', GenerateExcelPurchaseView.as_view(), name='purchase_excel'),
    path('generate-excel-purchase-year/', ExcelPurchaseYearView.as_view(), name='purchase_year_excel'),
    path('generate-excel-purchase-month/', ExcelPurchaseMonthView.as_view(), name='purchase_month_excel'),
    path('generate-excel-purchase-day/', ExcelPurchaseDayView.as_view(), name='purchase_day_excel'),
    
    #Reporte Ganancias
    path('profit-report/', ProfitReportView.as_view(), name='profit_report'),
    path('generate-pdf-profit/', GeneratePDFProfitView.as_view(), name='profit_pdf'),
    path('generate-pdf-profit-year/', YearlyPDFProfitView.as_view(), name='profit_year_pdf'),
    path('generate-pdf-profit-month/', MonthlyPDFProfitView.as_view(), name='profit_month_pdf'),
    path('generate-pdf-profit-day/', DailyPDFProfitView.as_view(), name='profit_day_pdf'),
    
    path('generate-excel-profit/', GenerateExcelProfitView.as_view(), name='profit_excel'),
    path('generate-excel-profit-year/', YearlyExcelProfitView.as_view(), name='profit_year_excel'),
    path('generate-excel-profit-month/', MonthlyExcelProfitView.as_view(), name='profit_month_excel'),
    path('generate-excel-profit-day/', DailyExcelProfitView.as_view(), name='profit_day_excel'),
    
    # miscelanea report
    path('mix-report/', MixReportView.as_view(), name='mix_report'),
    path('supplier-pdf/', SupplierPDFView.as_view(), name='supplier_pdf'),
    path('supplier-product-pdf/', SupplierProductPDFView.as_view(), name='supplier_product_pdf'),
    path('product-pdf/', ProductPDFView.as_view(), name='product_pdf'),
    path('productqty-pdf/', ProductPDFQtyView.as_view(), name='productqty_pdf'),
    
    path('supplier-excel/', SupplierExcelView.as_view(), name='supplier_excel'),
    path('supplier-product-excel/', SupplierProductExcelView.as_view(), name='supplier_product_excel'),
    path('product-excel/', ProductExcelView.as_view(), name='product_excel'),
    path('product-qty-excel/', ProductQtyExcelView.as_view(), name='productqty_excel'),
    
    path('mix-sales-pdf/', MixPDFSalesDayView.as_view(), name='mix_sales_pdf'),
    path('mix-tramo-sales-pdf/', MixTramoPDFSalesDayView.as_view(), name='mixtramo_sales_pdf'),
    
    path('mix-day-excel/', MixExcelSalesDayView.as_view(), name='mix_sales_excel'),
    path('mix-section-day-excel/', MixTramoExcelSalesDayView.as_view(), name='mix_sectionsales_excel'),
]

store/store/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('inventory/', include('inventory.urls')),
    
    path('pos/', include('pos.urls')),
    path('purchase/', include('purchase.urls')),
    path('report/', include('report.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/templates/about.html
{% extends "base.html" %} {% load static %}{% block pageContent %}
<div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-12">
    <div class="mdc-card">
        <div class="d-flex justify-content-between">
            <h4 class="card-title mb-0">About Page</h4>
        </div>
    </div>
</div>
<hr> {% endblock pageContent %}

store/templates/base.html
{% comment %} base.html {% endcomment %}
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0"> {% if page_title %}
    <title>{{ page_title }} | Grocery POS</title>
    {% else %}
    <title>Grocery POS</title>
    {% endif %}

    <!-- jQuery (necesario para DataTables) -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

    <link rel="stylesheet" href="{% static 'posApp/assets/bootstrap/css/bootstrap.min.css' %}">

    <!-- plugins:css -->
    <link rel="stylesheet" href="{% static 'posApp/assets/material-admin/vendors/mdi/css/materialdesignicons.min.css' %}">
    <link rel="stylesheet" href="{% static 'posApp/assets/material-admin/vendors/css/vendor.bundle.base.css' %}">
    <!-- endinject -->
    <!-- Plugin css for this page -->
    <link rel="stylesheet" href="{% static 'posApp/assets/material-admin/vendors/flag-icon-css/css/flag-icon.min.css' %}">
    <link rel="stylesheet" href="{% static 'posApp/assets/material-admin/vendors/jvectormap/jquery-jvectormap.css' %}">
    <!-- End plugin css for this page -->
    <!-- Layout styles -->
    <link rel="stylesheet" href="{% static 'posApp/assets/material-admin/css/demo/style.css' %}">
    <link rel="stylesheet" href="{% static 'posApp/assets/select2/dist/css/select2.min.css' %}">
    <!-- End layout styles -->
    <link rel="stylesheet" href="{% static 'posApp/assets/default/css/style.css' %}">
    <link rel="shortcut icon" href="{% static 'posApp/assets/material-admin/images/favicon.png' %}" />


    <script src="{% static 'posApp/assets/default/js/jquery-3.6.0.min.js' %}"></script>
    <script src="{% static 'posApp/assets/bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'posApp/assets/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'posApp/assets/bootstrap/js/popper.min.js' %}"></script>


    <!-- DataTables CSS -->
    <link rel="stylesheet" href="https://cdn.datatables.net/1.13.4/css/dataTables.bootstrap5.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/buttons/2.3.6/css/buttons.bootstrap5.min.css">

</head>

<body>
    <script src="{% static 'posApp/assets/material-admin/js/preloader.js' %}"></script>
    <div class="body-wrapper">
        <!-- Aside -->
        {% block navigation %} {% include "navigation.html" %} {% endblock navigation %}
        <!-- Aside -->
        <div class="main-wrapper mdc-drawer-app-content">
            <!-- Top Navigation -->
            {% block TopNavigation %} {% include "TopNavigation.html" %} {% endblock TopNavigation %}
            <!-- Top Navigation -->

            <div class="page-wrapper mdc-toolbar-fixed-adjust">
                <main class="content-wrapper">
                    <!-- Message -->
                    {% if messages %}
                    <div class="mdc-layout-grid py-1">
                        <div class="mdc-layout-grid__inner">
                            {% for message in messages %}
                            <div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-12">
                                <div class="alert alert-{{message.tags}} w-100 rounded-0 mb-0">
                                    <div class="d-flex w-100">
                                        <div class="col-auto flex-shrink-1 flex-grow-1">{{ message }}</div>
                                        <div class="col-auto text-center">
                                            <button class="btn-close btn-sm text-sm" type="button" onclick="$(this).closest('.alert').remove()"></button>
                                        </div>
                                    </div>

                                </div>
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                    {% endif %}
                    <!-- Message -->
                    <div class="mdc-layout-grid">
                        <div class="mdc-layout-grid__inner  page-content-container">
                            {% block pageContent %} {% endblock pageContent %}
                        </div>
                    </div>
                </main>
                <!-- partial:partials/_footer.html -->
                <footer>
                    <div class="mdc-layout-grid">
                        <div class="mdc-layout-grid__inner">
                            <div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-6-desktop">
                                <span class="text-center text-sm-left d-block d-sm-inline-block tx-14">Desarrollado por <a href="https://twitter.com/Wa_ViGo" target="_blank">.()wArt</a> {% now 'Y' %}</span>
                            </div>
                        </div>
                    </div>
                </footer>
                <!-- partial -->
            </div>
        </div>
    </div>
    {% block ScriptBlock %} {% endblock ScriptBlock %}
    <div class="modal fade" id="uni_modal" role='dialog'>
        <div class="modal-dialog modal-md modal-dialog-centered" role="document">
            <div class="modal-content rounded-0">
                <div class="modal-header">
                    <h5 class="modal-title"></h5>
                </div>
                <div class="modal-body">
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn  btn-sm btn-flat btn-primary rounded-0" id='submit' onclick="$('#uni_modal form').submit()">Guardar</button>
                    <button type="button" class="btn btn-sm btn-flat btn-secondary rounded-0" data-bs-dismiss="modal">Cancelar</button>
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade" id="confirm_modal" role='dialog'>
        <div class="modal-dialog modal-md modal-dialog-centered" role="document">
            <div class="modal-content rounded-0">
                <div class="modal-header">
                    <h5 class="modal-title">Confirmacion</h5>
                </div>
                <div class="modal-body">
                    <div id="delete_content"></div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-sm btn-flat btn-primary rounded-0" id='confirm' onclick="">Continuar</button>
                    <button type="button" class="btn btn-sm btn-flat btn-secondary rounded-0" data-bs-dismiss="modal">Cerrar</button>
                </div>
            </div>
        </div>
    </div>
    
    <script>
        window.start_loader = function() {
            $('body').removeClass('loaded')
        }
        window.end_loader = function() {
            $('body').addClass('loaded')
        }
        window.uni_modal = function($title = '', $url = '', $size = "") {
            start_loader()
            $.ajax({
                url: $url,
                error: err => {
                    console.log()
                    alert("An error occured")
                },
                success: function(resp) {
                    if (resp) {
                        $('#uni_modal .modal-title').html($title)
                        $('#uni_modal .modal-body').html(resp)
                        if ($size != '') {
                            $('#uni_modal .modal-dialog').addClass($size + '  modal-dialog-centered')
                        } else {
                            $('#uni_modal .modal-dialog').removeAttr("class").addClass("modal-dialog modal-md modal-dialog-centered")
                        }
                        $('#uni_modal').modal({
                            backdrop: 'static',
                            keyboard: false,
                            focus: true
                        })
                        $('#uni_modal').modal('show')
                        end_loader()
                    }
                }
            })
        }
        window._conf = function($msg = '', $func = '', $params = []) {
            $('#confirm_modal #confirm').attr('onclick', $func + "(" + $params.join(',') + ")")
            $('#confirm_modal .modal-body').html($msg)
            $('#confirm_modal').modal('show')
        }
        $(function() {

        })
    </script>

    <script src="{% static 'posApp/assets/material-admin/vendors/js/vendor.bundle.base.js' %}"></script>
    <script src="{% static 'posApp/assets/material-admin/js/material.js' %}"></script>
    <script src="{% static 'posApp/assets/material-admin/js/misc.js' %}"></script>
    <script src="{% static 'posApp/assets/material-admin/js/dashboard.js' %}"></script>
    <script src="{% static 'posApp/assets/select2/dist/js/select2.full.js' %}"></script>

    <!-- Bootstrap Bundle JS (incluye Popper) -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.3.0/js/bootstrap.bundle.min.js"></script>
    <!-- DataTables JS -->
    <script src="https://cdn.datatables.net/1.13.4/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.13.4/js/dataTables.bootstrap5.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/2.3.6/js/dataTables.buttons.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/2.3.6/js/buttons.bootstrap5.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/2.3.6/js/buttons.html5.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/2.3.6/js/buttons.print.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/2.3.6/js/buttons.colVis.min.js"></script>

</body>

</html>

store/templates/home.html
{% extends "base.html" %} 
{% load static %}{% load humanize %} {% block pageContent %}
<div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-12">
    <div class="mdc-card">
        <div class="d-flex justify-content-between">
            <h4 class="card-title mb-0">Home Page</h4>
        </div>
    </div>
</div>
<div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-12">
    <hr class="w-100">
</div>
<div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-3-desktop mdc-layout-grid__cell--span-3-tablet">
    <div class="mdc-card info-card info-card--success">
        <div class="card-inner">
            <h5 class="card-title">
                <a href="{% url 'inventory:category_list' %}">Categories</a>
            </h5>
            <h5 class="font-weight-light pb-2 mb-1 border-bottom">{{ categories|intcomma }}</h5>
            <p class="tx-12 text-muted">Number of Categories</p>
            
            <div class="card-icon-wrapper">
                <i class="material-icons">list</i>
            </div>
        </div>
    </div>
</div>
<div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-3-desktop mdc-layout-grid__cell--span-3-tablet">
    <div class="mdc-card info-card info-card--primary">
        <div class="card-inner">
            <h5 class="card-title">
                <a href="{% url 'inventory:product_list' %}">Products</a>
            </h5>
            <h5 class="font-weight-light pb-2 mb-1 border-bottom">{{ products|intcomma }}</h5>
            <p class="tx-12 text-muted">Number of Products</p>
            <div class="card-icon-wrapper">
                <i class="material-icons">label</i>
            </div>
        </div>
    </div>
</div>
<div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-3-desktop mdc-layout-grid__cell--span-3-tablet">
    <div class="mdc-card info-card info-card--info">
        <div class="card-inner">
            <h5 class="card-title">
                <a href="{% url 'pos:sales-page' %}">Today's Transactions</a>
            </h5>
            <h5 class="font-weight-light pb-2 mb-1 border-bottom">{{ transaction|intcomma }}</h5>
            <p class="tx-12 text-muted">Number of Today's Transactions</p>
            <div class="card-icon-wrapper">
                <i class="material-icons">receipt</i>
            </div>
        </div>
    </div>
</div>
<div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-3-desktop mdc-layout-grid__cell--span-3-tablet">
    <div class="mdc-card info-card info-card--warning">
        <div class="card-inner">
            <h5 class="card-title">Today's Sales</h5>
            <h5 class="font-weight-light pb-2 mb-1 border-bottom">{{ total_sales|intcomma }}</h5>
            <p class="tx-12 text-muted">Total Sales Today</p>
            <div class="card-icon-wrapper">
                <i class="mdi mdi-cash-multiple"></i>
            </div>
        </div>
    </div>
</div>
<div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-3-desktop mdc-layout-grid__cell--span-3-tablet">
    <div class="mdc-card info-card info-card--warning">
        <div class="card-inner">
            <h5 class="card-title">
                <a href="{% url 'purchase:supplier_list' %}">Today's Transactions</a>
            </h5>
            <h5 class="font-weight-light pb-2 mb-1 border-bottom">{{ total_sales|intcomma }}</h5>
            <p class="tx-12 text-muted">Total Sales Today</p>
            <div class="card-icon-wrapper">
                <i class="mdi mdi-cash-multiple"></i>
            </div>
        </div>
    </div>
</div>

<div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-3-desktop mdc-layout-grid__cell--span-3-tablet">
    <div class="mdc-card info-card info-card--warning">
        <div class="card-inner">
            <h5 class="card-title">
                <a href="{% url 'report:mix_report' %}">Daily Transaction Reports</a>
            </h5>
            <h5 class="font-weight-light pb-2 mb-1 border-bottom">{{ total_sales|intcomma }}</h5>
            <p class="tx-12 text-muted">Total Sales Today</p>
            <div class="card-icon-wrapper">
                <i class="mdi mdi-cash-multiple"></i>
            </div>
        </div>
    </div>
</div>
{% endblock pageContent %}

store/templates/navigation.html
{% load static %}
<!-- partial:partials/_sidebar.html -->
<aside class="mdc-drawer mdc-drawer--dismissible mdc-drawer--open bg-dark bg-gradient">
    <div class="mdc-drawer__header border-bottom border-light">
        <a href="{% url 'home-page' %}" class="brand-logo">
            <h3 class="text-center text-light">POINT OF SALE</h3>
            <h3 class="text-center text-light">STORE</h3>
        </a>
    </div>
    <div class="mdc-drawer__content">
        <div class="mdc-list-group">
            <nav class="mdc-list mdc-drawer-menu">
                <div class="mdc-list-item mdc-drawer-item">
                    <a class="mdc-drawer-link" href="{% url 'home-page' %}">
                        <i class="material-icons mdc-list-item__start-detail mdc-drawer-item-icon" aria-hidden="true">home</i> Home
                    </a>
                </div>

                <hr class="separator" style="margin: 5px 0;">
                <div class="mdc-list-item mdc-drawer-item">
                    <a class="mdc-drawer-link" href="{% url 'pos:pos-page' %}">
                        <i class="material-icons mdc-list-item__start-detail mdc-drawer-item-icon" aria-hidden="true">store</i> POS
                    </a>
                </div>
                <div class="mdc-list-item mdc-drawer-item">
                    <a class="mdc-drawer-link" href="{% url 'pos:sales-page' %}">
                        <i class="material-icons mdc-list-item__start-detail mdc-drawer-item-icon" aria-hidden="true">receipt</i> Sales
                    </a>
                </div>

                <hr class="separator" style="margin: 5px 0;">
                <div class="mdc-list-item mdc-drawer-item">
                    <a class="mdc-drawer-link" href="{% url 'inventory:category_list' %}">
                        <i class="material-icons mdc-list-item__start-detail mdc-drawer-item-icon" aria-hidden="true">list</i> Category List
                    </a>
                </div>
                <div class="mdc-list-item mdc-drawer-item">
                    <a class="mdc-drawer-link" href="{% url 'inventory:product_list' %}">
                        <i class="material-icons mdc-list-item__start-detail mdc-drawer-item-icon" aria-hidden="true">label</i> Product List
                    </a>
                </div>

                <hr class="separator" style="margin: 5px 0;">
                <div class="mdc-list-item mdc-drawer-item">
                    <a class="mdc-drawer-link" href="{% url 'purchase:supplier_list' %}">
                        <i class="material-icons mdc-list-item__start-detail mdc-drawer-item-icon" aria-hidden="true">local_shipping</i> Suppliers
                    </a>
                </div>
                <div class="mdc-list-item mdc-drawer-item">
                    <a class="mdc-drawer-link" href="{% url 'purchase:purchase_list' %}">
                        <i class="material-icons mdc-list-item__start-detail mdc-drawer-item-icon" aria-hidden="true">shopping_cart</i> Product Purchases
                    </a>
                </div>

                <hr class="separator" style="margin: 5px 0;">
                
                <div class="mdc-list-item mdc-drawer-item">
                    <a class="mdc-drawer-link" href="{% url 'report:mix_report' %}">
                        <i class="material-icons mdc-list-item__start-detail mdc-drawer-item-icon" aria-hidden="true">shuffle</i> Miscellaneous
                    </a>
                </div>
                <div class="mdc-list-item mdc-drawer-item">
                    <a class="mdc-drawer-link" href="{% url 'report:sales_report' %}">
                        <i class="material-icons mdc-list-item__start-detail mdc-drawer-item-icon" aria-hidden="true">shopping_cart</i> Sales Report
                    </a>
                </div>
                <div class="mdc-list-item mdc-drawer-item">
                    <a class="mdc-drawer-link" href="{% url 'report:reporte_compras' %}">
                        <i class="material-icons mdc-list-item__start-detail mdc-drawer-item-icon" aria-hidden="true">shopping_basket</i> Purchase Report
                    </a>
                </div>
                <div class="mdc-list-item mdc-drawer-item">
                    <a class="mdc-drawer-link" href="{% url 'report:profit_report' %}">
                        <i class="material-icons mdc-list-item__start-detail mdc-drawer-item-icon" aria-hidden="true">attach_money</i> Profit Report
                    </a>
                </div>
            </nav>
        </div>
    </div>
</aside>

store/templates/topNavigation.html
{% load static %}
<!-- partial:partials/_navbar.html -->
<header class="mdc-top-app-bar border-bottom shadow">
    <div class="mdc-top-app-bar__row">
        <div class="mdc-top-app-bar__section mdc-top-app-bar__section--align-start">
            <button class="material-icons mdc-top-app-bar__navigation-icon mdc-icon-button sidebar-toggler">menu</button>
        </div>
        <div class="mdc-top-app-bar__section mdc-top-app-bar__section--align-end mdc-top-app-bar__section-right">
            <div class="menu-button-container menu-profile d-none d-md-block">
                <button class="mdc-button mdc-menu-button">
                    <span class="d-flex align-items-center">
                    <span class="figure">
                        <img src="{% static 'posApp/assets/material-admin/images/faces/ava.jpg' %}" alt="user" class="user">
                    </span>
                    <span class="user-name">{{ user.first_name }}</span>
                    </span>
                </button>
                <div class="mdc-menu mdc-menu-surface" tabindex="-1">
                    <ul class="mdc-list" role="menu" aria-hidden="true" aria-orientation="vertical">
                        <li class="mdc-list-item" role="menuitem">
                            <div class="item-thumbnail item-thumbnail-icon-only">
                                <i class="mdi mdi-account text-dark"></i>
                            </div>
                            <div class="item-content d-flex align-items-start flex-column justify-content-center">
                                <h6 class="item-subject font-weight-normal">
                                    {{ user.username }}
                                </h6>
                            </div>
                        </li>
                        <li class="mdc-list-item" role="menuitem">
                            <a class="text-dark" href="{% url 'redirect-admin' %}">
                                <div class="item-thumbnail item-thumbnail-icon-only">
                                    <i class="mdi mdi-settings-outline text-dark"></i>
                                </div>
                                <div class="item-content d-flex align-items-start flex-column justify-content-center">
                                    <h6 class="item-subject font-weight-normal">
                                        Admin
                                    </h6>
                                </div>
                            </a>
                        </li>
                        <li class="mdc-list-item" role="menuitem">
                            <a class="text-dark" href="{% url 'logout' %}">
                                <div class="item-thumbnail item-thumbnail-icon-only">
                                    <i class="mdi mdi-logout text-dark"></i>
                                </div>
                                <div class="item-content d-flex align-items-start flex-column justify-content-center">
                                    <h6 class="item-subject font-weight-normal">Logout</h6>
                                </div>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</header>
<!-- partial -->